### ISSUE TITLE
Create UI frontend for jukebox deployer

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/tf_jukebox#16]
we need a UI looks like the UI of our products (vdc, 3bot,... deployers)

# issues
- [x] mockups here https://github.com/threefoldtech/tf_jukebox/issues/14
- [x] frontend UI
- [x] logo https://github.com/threefoldtech/tf_jukebox/issues/20

**Comment by mhost39** [comment]
Verified 
branch: development

![image](https://user-images.githubusercontent.com/31102305/123274324-b5fff200-d503-11eb-95ef-f93639bb8a25.png)
![image](https://user-images.githubusercontent.com/31102305/123274414-c9ab5880-d503-11eb-828e-5d69cad8468e.png)
![image](https://user-images.githubusercontent.com/31102305/123274517-df208280-d503-11eb-82a8-92551db81081.png)
