### ISSUE TITLE
remove kubectl from digibyte image

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/tf_jukebox#40]
Digibyte image showing kubectl exec on its home page which should be removed because we don't use kubernetes
![Screenshot from 2021-06-10 14-14-27](https://user-images.githubusercontent.com/1689456/121859086-942e9000-ccf7-11eb-8692-91bec7e8e12e.png)

**Comment by mhost39** [comment]
Verified 
![image](https://user-images.githubusercontent.com/31102305/123542860-200ad800-d74c-11eb-908d-783158bd8843.png)
