### ISSUE TITLE
Add service to update deployment instance

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tf_jukebox#45]
checks workloads from explorer if anything changes, update the deployment instance.

**Comment by mhost39** [comment]
Verified 
branch: development 

before delete workload from explorer:
![image](https://user-images.githubusercontent.com/31102305/123543716-2f8c2000-d750-11eb-8057-71dc3b097106.png)

after 5 minute from deletion:
 
![image](https://user-images.githubusercontent.com/31102305/123544397-59931180-d753-11eb-822e-9bf1cc953f07.png)
