### ISSUE TITLE
Add service for self-healing the deployments

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tf_jukebox#46]
when a node or more went down, this service should redeploy the down nodes.

**Comment by mhost39** [comment]
Verified 
branch: development

node went down:
![image](https://user-images.githubusercontent.com/31102305/123546934-f9a26800-d75e-11eb-9c25-6402db343949.png)

after 2 hours:
![image](https://user-images.githubusercontent.com/31102305/123547011-4b4af280-d75f-11eb-8ac4-a903a7c378ff.png)
