### ISSUE TITLE
As a user I want to list my blockchain nodes

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/tf_jukebox#5]
the user should be able to list hist nodes
https://github.com/threefoldtech/tf_jukebox/issues/18
https://github.com/threefoldtech/tf_jukebox/issues/17

**Comment by mhost39** [comment]
Verified
commit: ae6f1c8120eb3b501528fc8f0d955dce27d5b811
branch: development
![image](https://user-images.githubusercontent.com/31102305/123276599-98cc2300-d505-11eb-8edf-cfbdb83baa7f.png)
