### ISSUE TITLE
Add action for extending the deployment with more nodes

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tf_jukebox#51]
This button should be in deployment actions and redirect to a chatflow to pay for the number of nodes entered.

**Comment by mhost39** [comment]
Verified 
commit: 51af51c1a618847ba92754fadbce38d72bd1a27f
branch: development
![image](https://user-images.githubusercontent.com/31102305/123298995-5dd3ea80-d519-11eb-80c4-6d75f53e55ff.png)
