### ISSUE TITLE
Auto extend may not expire in time

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/tf_jukebox#58]
Auto extend  service may not extend a solution with auto extend enabled in time. Need to manually be able to extend if there are enough funds

**Comment by ranatrk** [comment]
![Screenshot from 2021-06-23 18-30-03](https://user-images.githubusercontent.com/17128393/123135219-d4a5b080-d451-11eb-8d1f-7a48afce3d81.png)

**Comment by mhost39** [comment]
Verified 
branch: development
commit: 47baebb1bb10aca2854ec0595b9839ed8c5e9b9d
![image](https://user-images.githubusercontent.com/31102305/123298714-12b9d780-d519-11eb-9f21-a41570c24d4c.png)
