### ISSUE TITLE
Show details of the fund needed for auto extend

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/tf_jukebox#59]
Show the detailed of the total price shown that needs to be funded to the wallet for auto extension to be successful for the deployments

**Comment by ranatrk** [comment]
![Screenshot from 2021-06-23 18-29-26](https://user-images.githubusercontent.com/17128393/123135226-d5d6dd80-d451-11eb-9c4d-4aa3f8b6f227.png)

**Comment by mhost39** [comment]
Verified 
commit: 47baebb1bb10aca2854ec0595b9839ed8c5e9b9d
branch: development
![image](https://user-images.githubusercontent.com/31102305/123297654-0ed98580-d518-11eb-8955-bc766d09bdd6.png)
