### ISSUE TITLE
As a user I want to check my node info

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/tf_jukebox#6]
the user should be able to view specific node info, this should includes expiration time
https://github.com/threefoldtech/tf_jukebox/issues/18
https://github.com/threefoldtech/tf_jukebox/issues/17

**Comment by mhost39** [comment]
Verified
commit: a2fdecb6503e32128376edba29d80eebb2e463bc
branch: development
![image](https://user-images.githubusercontent.com/31102305/123273787-3bcf6d80-d503-11eb-93df-1a1bc8f28fdd.png)
