### ISSUE TITLE
After a failed deployment, it didn't refund

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tf_jukebox#68]
![image](https://user-images.githubusercontent.com/41957921/124489731-9d1ff800-ddb1-11eb-8ed0-845b8e0d4ba8.png)

<img src="https://user-images.githubusercontent.com/41957921/124489925-ce98c380-ddb1-11eb-8c3a-52c66962d1ce.png" width="350" height="500">

**Comment by AhmedHanafy725** [comment]
After checking the deployer alerts, it found that the deployment was done, but it failed to extend it.

![image](https://user-images.githubusercontent.com/41957921/124491774-ed985500-ddb3-11eb-90f7-74ac3e239b02.png)

As a solution, we will not delete the deployment, and it will available for an hour, so it can be extended manually.
Also, the tokens are in the funding wallet and will allow deployment without payment in case of the funding wallet has enough tokens for the deployment. 
```python
JS-NG> j.clients.stellar.jukebox_kristine.get_balance()                                                                                      
Balances
  5.2228500 TFT:GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47
  2.5999900 XLM
```

**Comment by Vilnite** [comment]
After 2 failed deployments that both took payment but didn't deploy my Funding Wallet is empty as well as no refund has been sent to TF Connect wallet.

<img width="1552" alt="Screenshot 2021-07-07 at 09 48 35" src="https://user-images.githubusercontent.com/20182572/124713478-475e6380-df09-11eb-9d1f-145269cc4dc7.png">

**Comment by AhmedHanafy725** [comment]
@Vilnite I can't see any deployment done on devnet machine, but you have deployments on the staging machine https://staging.blockchainjukebox.com, can you check the funding wallet there?

**Comment by Vilnite** [comment]
My bad. Not sure where I got devnet link.

Staging is refunded in Funding Wallet. Thank you.

<img width="1117" alt="Screenshot 2021-07-07 at 14 10 43" src="https://user-images.githubusercontent.com/20182572/124749687-36bfe480-df2d-11eb-82e7-f857cc1107b6.png">
