### ISSUE TITLE
As a user I want to be able to delete nodes

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/tf_jukebox#7]
user should be able to delete nodes
https://github.com/threefoldtech/tf_jukebox/issues/18
https://github.com/threefoldtech/tf_jukebox/issues/17

**Comment by mhost39** [comment]
Verified 
commit: a2fdecb6503e32128376edba29d80eebb2e463bc
branch: development
![image](https://user-images.githubusercontent.com/31102305/123272978-8997a600-d502-11eb-8f4f-47ba7d445a06.png)
