### ISSUE TITLE
Invalid expiration date

### ISSUE THREAD

**Issue by Vilnite** [threefoldtech/tf_jukebox#70]
Whatever I put in (tried Digibyte and Dash) it gives Invalid Date

<img width="1552" alt="Screenshot 2021-07-07 at 09 50 41" src="https://user-images.githubusercontent.com/20182572/124713709-8ee4ef80-df09-11eb-8d70-35581c172629.png">

Stuck at this deployment step.

**Comment by xmonader** [comment]
Is that Safari btw?

**Comment by AhmedHanafy725** [comment]
we tried that on Mac, it worked on Chrome but didn't work on Safari, and we don't support Safari.

**Comment by Vilnite** [comment]
Indeed the problem is Safari. Works on Chrome. Definitely needs to be pointed somewhere that Jukebox doesn't support Safari browser for all mac people out there.
