### ISSUE TITLE
Blocked at Farm selection

### ISSUE THREAD

**Issue by Vilnite** [threefoldtech/tf_jukebox#71]
Gives me error at Farm selection step for all solutions:

<img width="1552" alt="Screenshot 2021-07-08 at 10 20 32" src="https://user-images.githubusercontent.com/20182572/124879925-6545ca00-dfd6-11eb-82ee-d0925eb06e62.png">

**Comment by AhmedHanafy725** [comment]
testnet explorer cert is expired https://github.com/threefoldtech/tf_operations/issues/203

**Comment by Vilnite** [comment]
It's deploying now. 
Can we make sure all is up and running? Would be nice if we can show live a successful deployment process today on lunch hang. :)

**Comment by AhmedHanafy725** [comment]
@Vilnite it should be working now, can you try again?

**Comment by Vilnite** [comment]
Initializing deployment. Been 5 min now.

**Comment by Vilnite** [comment]
Didn't succeed.

<img width="1433" alt="Screenshot 2021-07-08 at 11 21 04" src="https://user-images.githubusercontent.com/20182572/124889178-747d4580-dfdf-11eb-873e-0112ac8290c5.png">

**Comment by AhmedHanafy725** [comment]
There is a problem with paying for pools on testnet https://github.com/threefoldtech/tf_operations/issues/204

**Comment by AhmedHanafy725** [comment]
@Vilnite I think the problem now fixed, you can try now
