### ISSUE TITLE
Update Presearch deployment step

### ISSUE THREAD

**Issue by Vilnite** [threefoldtech/tf_jukebox#75]
This is confusing as I don't know where to get a code:

<img width="1215" alt="Screenshot 2021-07-14 at 11 35 02" src="https://user-images.githubusercontent.com/20182572/125591440-3b69b591-8471-42ee-80fe-e52c1aed6652.png">

Add to this step:
Register your node and get a registration code at https://nodes.presearch.org/dashboard

**Comment by ashraffouda** [comment]
![Screenshot from 2021-07-25 18-12-09](https://user-images.githubusercontent.com/1689456/126905875-b1d60abf-784f-4b39-abaf-a081458eabfd.png)
