### ISSUE TITLE
Jukebox flists update 

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/tf_jukebox#86]
currently we found some images that needs to be updated every now and then like presearch 
so we need to have a restart button which the user can restart all instances in the deployment so they got updated with the new flist 
for new deployments should be working after this issue is done https://github.com/threefoldtech/tf-images/issues/49

**Comment by gmachtel** [comment]
2 triggers are needed to make it work: 
- new Docker triggers generation of new flist
- new flist triggers relaunch of the container with the new image

**Comment by Vilnite** [comment]
Moved to circles tool: https://circles.threefold.me/project/despiegk-proj_jukebox/us/70?kanban-status=1434
