### ISSUE TITLE
Presearch is not working properly

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/tf_jukebox#87]
presearch now not working with multiple deployments on the same farm, this is because it requires ipv4
so we need to do either one of the following 
- grid 2 containers to support ipv4
- deploy presearch using terraform on grid3 (until we move all Jukebox to grid3)
- deploy nodes on a vm (this will require more work)

**Comment by Vilnite** [comment]
Focus on deploying on Grid 3.0.

Moving planning and high level tasks (issues) to circles tool:
https://circles.threefold.me/project/despiegk-proj_jukebox/us/69?kanban-status=1577
