### ISSUE TITLE
As a user I want to be notified for the pools that are about to expire and support auto extend

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/tf_jukebox#9]
user should be notified before nodes expiration time if his wallet doesn't have enough money
user should be able to extend running time of nodes
if the user wallet has enough money > we automatically extend his pool
if he doesn't have enough moeny > we send him notification that the pool is about to expire and then he can add money to his wallet for the extension to happen

**Comment by mhost39** [comment]
Verified
branch: development
![image](https://user-images.githubusercontent.com/31102305/123550399-89e7a980-d76d-11eb-9b7d-9c3b07ae828e.png)

**Comment by mhost39** [comment]
Verified
branch: development
![image](https://user-images.githubusercontent.com/31102305/123550399-89e7a980-d76d-11eb-9b7d-9c3b07ae828e.png)
